# Permalinks
permalink:           /blog/:title/

# Setup
title:               Oli Frost
tagline:             Novelty songs about the climate crisis, mostly. Also known as Oliver Frost, Ollie Frost, Olly Frost, or however you misspelt it.
description:         Novelty songs about the climate crisis, mostly. Also known as Oliver Frost, Ollie Frost, Olly Frost, or however you misspelt it.
footer:              Oliver Frost, Ollie Frost, Olly Frost, or however you misspell it.

exclude:             [/psd/]

# Markdown
collections:
  hidden:
    output: true
    permalink: /work/:title/
    sort_by: order
  shop:
    output: true
    permalink: /shop/:title/
    sort_by: order


# SASS
sass:
  sass_dir:          _sass
  style:            compressed
  encoding:          utf-8

# Google Analytics
analytics_id:  UA-111675559-1


# SEO
author:
  name: Oli Frost
  twitter: olifro_st
  instagram: olifro.st
  youtube: olifrost
  spotify: https://open.spotify.com/artist/5dFJdXPDdubN7e6RIC2MXP?si=hjjqqrAKROazng3zJ9SKag
  tiktok: olifro.st
  email: mail@olifro.st

defaults:
  - scope:
      path: ""
    values:
      image: /blog/olifrost.jpg

profile: /blog/olifrost.jpg

twitter:
  username: olifro_st

social:
  name: Oli Frost
  links:
    - https://twitter.com/olifro_st
    - https://instagram.com/olifro.st
    - https://youtube.com/c/olifrost

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
