# Permalinks
permalink:           /blog/:title/

# Setup
title:               Oli Frost
tagline:             Also known as Oliver Frost, Ollie Frost, Olly Frost, or however you misspelt it.
description:         Also known as Oliver Frost, Ollie Frost, Olly Frost, or however you misspelt it.
footer:              Oliver Frost, Ollie Frost, Olly Frost, or however you misspell it.

exclude:             [/psd/]


# Markdown
collections:
  portfolio:
    # output: true
    permalink: /work/:title/
  causes:
    # output: true
    permalink: /work/:title/
  brands:
    # output: true
    permalink: /work/:title/
  hidden:
    output: true
    permalink: /work/:title/
  refrost:
    # output: true
    permalink: /work/:title/


# SASS
sass:
  sass_dir:          _sass
  style:            compressed
  encoding:          utf-8

# Google Analytics
analytics_id:  UA-111675559-1


# SEO
author:
  name: Oli Frost
  twitter: realolifrost
  instagram: realolifrost
  youtube: olifrost
  email: mail@olifro.st

defaults:
  - scope:
      path: ""
    values:
      image: /blog/refrosttheplanet-large.jpg

profile: /img/olifrot.jpg

twitter:
  username: realolifrost

social:
  name: Oli Frost
  links:
    - https://twitter.com/realolifrost
    - https://instagram.com/realolifrost
    - https://youtube.com/c/realolifrost

# Gems
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
